### ISSUE TITLE
possible autoformat improvement

### ISSUE THREAD

**Issue by kloimhardt** [oakes/cross-parinfer#2]
In the Nightlight editor, when I trigger autoformat
```
;;insert blank in front of next line to trigger autoformat
(comment 
 (def foo
     :foo)
 foo)
```
I get the unexpected result
```
;;insert blank in front of next line to trigger autoformat 
 (comment 
   (def foo
     :foo))
 foo
```
If I comment out line 138 in cross-parinfer.core
```
#_(not= indent current-indent)
```
I get the expected result
```
;;insert blank in front of next line to trigger autoformat 
 (comment 
   (def foo
     :foo)
   foo)
```

**Comment by oakes** [comment]
I added the fix. I don't remember why I added that conditional, so I'll release new versions of nightcode/nightlight with the change and we'll find out if there was a reason :-)

**Comment by oakes** [comment]
Nightlight 1.9.3 has this change FYI.
